"""create equipment fueltype mapping table

Revision ID: 007
Revises: 006
Create Date: 2025-01-11 17:07:24.923076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: Union[str, None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment_fuel",
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.Column("fuel_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["fuel_type_id"],
            ["fuel_type.id"],
        ),
        sa.PrimaryKeyConstraint("equipment_id", "fuel_type_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipment_fuel")
    # ### end Alembic commands ###
