"""create power_speed_curve table

Revision ID: 009
Revises: 008
Create Date: 2025-01-19 14:21:10.396333

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: Union[str, None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "power_speed_curve",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("speed_water", sa.Float(), nullable=False),
        sa.Column("me_power", sa.Float(), nullable=False),
        sa.Column("vessel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vessel_id"],
            ["vessel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("power_speed_curve")
    # ### end Alembic commands ###
