"""create meta data

Revision ID: f92875c2b496
Revises: 
Create Date: 2024-12-22 10:33:08.954645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f92875c2b496'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_cn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_abbr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cf', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_cn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_cn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explaination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_zone')
    op.drop_table('ship_type')
    op.drop_table('fuel_type')
    # ### end Alembic commands ###
